### PR TITLE
Enable support for 16.04

### PR DESCRIPTION
**Pull request by qzio**
(Duplicate of #5)

Test that is green on my machine:
- rspec
- rubocop
- kitchen `default-ubuntu-1604`.
- kitchen `test-ubuntu-1604`

### CODE REVIEW

**Comment by qzio** [comment]
Pretty sure the travis error is not related to this PR.
```
         File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open

           raise URLError(err)

       urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
```
Anyone knows if `master` still builds without errors on travis?

**Comment by chasebolt** [comment]
👍  need this merged in please

**Comment by bshaw** [comment]
+1

**Comment by qzio** [comment]
For ref: https://github.com/chef-cookbooks/docker supports 16.04 now-days.
I guess this will never be merged, closing.

**Pull request closed without merging**
